/*
 * Copyright 2012-2014, Luis Filipe da Cruz Nassif
 * 
 * This file is part of Indexador e Processador de Evidências Digitais (IPED).
 *
 * IPED is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * IPED is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with IPED.  If not, see <http://www.gnu.org/licenses/>.
 */
package dpf.sp.gpinf.indexer.database;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Properties;

import dpf.sp.gpinf.indexer.Configuration;

/*
 * Classe que contém as descrições das categorias do FTK4.2+, utilizadas em indexações de relatórios, as quais estão hard-coded.
 * Foram obtidas realizando alterações no banco de dados, setando a categoria de cada arquivo
 * idêntica ao seu id. Assim, ordenando os itens pelo id, obtemos a categoria correspondente a cada id.
 */
public class FTK42FileTypes {

	private static Map<Integer, String> mapTypeDesc;

	private static String CONFIG_FILE = "FTKCategoriesConfig.txt";

	public static void getFTK42FileTypes(String configPath) throws IOException {
		Properties properties = new Properties();
		File file = new File(configPath + "/conf/" + CONFIG_FILE);
		try {
			properties.load(new FileInputStream(file));
			mapTypeDesc = new HashMap<Integer, String>();
			for (int i = 0; i < 10000; i++) {
				String desc = properties.getProperty(String.valueOf(i));
				if (desc == null)
					break;
				mapTypeDesc.put(i, desc);
			}
		} catch (FileNotFoundException e) {
			System.out.println(new Date() + "\t[AVISO]\t" + " Arquivo não encontrado: " + file.getAbsolutePath());
			throw e;
		} catch (IOException e) {
			System.out.println(new Date() + "\t[AVISO]\t" + " Não foi possível ler " + file.getAbsolutePath());
			throw e;
		}

	}

	public static String getTypeDesc(int type) {

		if (mapTypeDesc == null) {
			try {
				getFTK42FileTypes(Configuration.configPath);

			} catch (Exception e) {

				mapTypeDesc = new HashMap<Integer, String>();
				mapTypeDesc.put(0, "File Category");
				mapTypeDesc.put(1, "Documents");
				mapTypeDesc.put(2, "Spreadsheets");
				mapTypeDesc.put(3, "Databases");
				mapTypeDesc.put(4, "Presentations");
				mapTypeDesc.put(5, "Graphics");
				mapTypeDesc.put(6, "Multimedia");
				mapTypeDesc.put(7, "Email");
				mapTypeDesc.put(8, "Executable");
				mapTypeDesc.put(9, "Archives");
				mapTypeDesc.put(10, "Folders");
				mapTypeDesc.put(11, "Slack/Free Space");
				mapTypeDesc.put(12, "Other Known Types");
				mapTypeDesc.put(13, "Unknown Types");
				mapTypeDesc.put(14, "Adobe Documents");
				mapTypeDesc.put(15, "Adobe Acrobat");
				mapTypeDesc.put(16, "Adobe FrameMaker Documents");
				mapTypeDesc.put(17, "Adobe FrameMaker");
				mapTypeDesc.put(18, "Adobe FrameMaker 3.0");
				mapTypeDesc.put(19, "Adobe FrameMaker 3.0 Japan");
				mapTypeDesc.put(20, "Adobe FrameMaker 4.0");
				mapTypeDesc.put(21, "Adobe FrameMaker 4.0 Japan");
				mapTypeDesc.put(22, "Adobe FrameMaker 5.0");
				mapTypeDesc.put(23, "Adobe FrameMaker 5.0 Japan");
				mapTypeDesc.put(24, "Adobe FrameMaker 5.5");
				mapTypeDesc.put(25, "Adobe FrameMaker 6.0");
				mapTypeDesc.put(26, "Adobe FrameMaker 6.0 Japan");
				mapTypeDesc.put(27, "Hangul");
				mapTypeDesc.put(28, "Hangul 97");
				mapTypeDesc.put(29, "Hangul 2002-2007");
				mapTypeDesc.put(30, "HTML and XML");
				mapTypeDesc.put(31, "HTML");
				mapTypeDesc.put(32, "Arabic HTML (ASMO-708)");
				mapTypeDesc.put(33, "Arabic HTML (DOS)");
				mapTypeDesc.put(34, "Arabic HTML (ISO)");
				mapTypeDesc.put(35, "Arabic HTML (Mac)");
				mapTypeDesc.put(36, "Arabic HTML (Win)");
				mapTypeDesc.put(37, "Baltic HTML (ISO)");
				mapTypeDesc.put(38, "Baltic HTML (Win)");
				mapTypeDesc.put(39, "Central Europe HTML (DOS)");
				mapTypeDesc.put(40, "Central Europe HTML (ISO)");
				mapTypeDesc.put(41, "Central Europe HTML (Mac)");
				mapTypeDesc.put(42, "Central Europe HTML (Win)");
				mapTypeDesc.put(43, "HTML - Chinese (Big 5)");
				mapTypeDesc.put(44, "HTML - Chinese (EUC)");
				mapTypeDesc.put(45, "HTML - Chinese (GB)");
				mapTypeDesc.put(46, "Chinese Simp HTML (EUC)");
				mapTypeDesc.put(47, "Chinese Simp HTML (Win (GB2312))");
				mapTypeDesc.put(48, "Chinese Trad HTML (Win (BIG5))");
				mapTypeDesc.put(49, "HTML - CSS");
				mapTypeDesc.put(50, "HTML - Cyrillic (ANSI 1251)");
				mapTypeDesc.put(51, "HTML - Cyrillic (KOI8-R)");
				mapTypeDesc.put(52, "Cyrillic HTML (DOS)");
				mapTypeDesc.put(53, "Cyrillic HTML (ISO)");
				mapTypeDesc.put(54, "Cyrillic HTML (KOI8-R)");
				mapTypeDesc.put(55, "Cyrillic HTML (Mac)");
				mapTypeDesc.put(56, "Cyrillic HTML (Win)");
				mapTypeDesc.put(57, "US/Portuguese EBCDIC HTML");
				mapTypeDesc.put(58, "Austrian/German EBCDIC HTML");
				mapTypeDesc.put(59, "Danish/Norwegian EBCDIC HTML");
				mapTypeDesc.put(60, "Finnish/Swedish EBCDIC HTML");
				mapTypeDesc.put(61, "Italian EBCDIC HTML");
				mapTypeDesc.put(62, "Spanish EBCDIC HTML");
				mapTypeDesc.put(63, "UK EBCDIC HTML");
				mapTypeDesc.put(64, "French EBCDIC HTML");
				mapTypeDesc.put(65, "Belgian EBCDIC HTML");
				mapTypeDesc.put(66, "East Europe EBCDIC HTML");
				mapTypeDesc.put(67, "Icelandic EBCDIC HTML");
				mapTypeDesc.put(68, "Turkish EBCDIC HTML");
				mapTypeDesc.put(69, "Greek HTML (ISO)");
				mapTypeDesc.put(70, "Greek HTML (Mac)");
				mapTypeDesc.put(71, "Greek HTML (Win)");
				mapTypeDesc.put(72, "Hebrew HTML (DOS)");
				mapTypeDesc.put(73, "Hebrew HTML (ISO)");
				mapTypeDesc.put(74, "Hebrew HTML (Win)");
				mapTypeDesc.put(75, "HTML - Japanese (EUC)");
				mapTypeDesc.put(76, "HTML - Japanese (JIS)");
				mapTypeDesc.put(77, "HTML - Japanese (Shift JIS)");
				mapTypeDesc.put(78, "Japanese HTML (Mac)");
				mapTypeDesc.put(79, "Japanese HTML (Win)");
				mapTypeDesc.put(80, "HTML - Korean");
				mapTypeDesc.put(81, "Korean HTML (Johab)");
				mapTypeDesc.put(82, "Korean HTML (Win)");
				mapTypeDesc.put(83, "HTML - Central European");
				mapTypeDesc.put(84, "HTML Unicode");
				mapTypeDesc.put(85, "AvantGo HTML");
				mapTypeDesc.put(86, "Compact HTML");
				mapTypeDesc.put(87, "Excel HTML");
				mapTypeDesc.put(88, "PowerPoint HTML");
				mapTypeDesc.put(89, "Web Clipping HTML");
				mapTypeDesc.put(90, "Word HTML");
				mapTypeDesc.put(91, "XHTML");
				mapTypeDesc.put(92, "XHTML Basic");
				mapTypeDesc.put(93, "HTML - SearchML");
				mapTypeDesc.put(94, "Wireless HTML");
				mapTypeDesc.put(95, "Russian HTML (DOS)");
				mapTypeDesc.put(96, "Thai HTML (Win)");
				mapTypeDesc.put(97, "Turkish HTML (DOS)");
				mapTypeDesc.put(98, "Turkish HTML (ISO)");
				mapTypeDesc.put(99, "Turkish HTML (Mac)");
				mapTypeDesc.put(100, "Turkish HTML (Win)");
				mapTypeDesc.put(101, "Vietnamese HTML (Win)");
				mapTypeDesc.put(102, "West Europe HTML (ISO)");
				mapTypeDesc.put(103, "West Europe HTML (Mac)");
				mapTypeDesc.put(104, "West Europe HTML (Win)");
				mapTypeDesc.put(105, "XML");
				mapTypeDesc.put(106, "XML DOCTYPE");
				mapTypeDesc.put(107, "HTML/Wireless Export");
				mapTypeDesc.put(108, "Flexiondoc 1 schema");
				mapTypeDesc.put(109, "Flexiondoc 2 schema");
				mapTypeDesc.put(110, "Flexiondoc 3 schema");
				mapTypeDesc.put(111, "Flexiondoc 4 schema");
				mapTypeDesc.put(112, "Flexiondoc 5 schema");
				mapTypeDesc.put(113, "Flexiondoc 5.1 schema");
				mapTypeDesc.put(114, "IBM");
				mapTypeDesc.put(115, "FFT");
				mapTypeDesc.put(116, "Revisable Form Text");
				mapTypeDesc.put(117, "Writing Assistant");
				mapTypeDesc.put(118, "Ichitaro");
				mapTypeDesc.put(119, "Ichitaro 3.0");
				mapTypeDesc.put(120, "Ichitaro 4.0");
				mapTypeDesc.put(121, "Ichitaro 8.0");
				mapTypeDesc.put(122, "JavaScript");
				mapTypeDesc.put(123, "JustWrite Documents");
				mapTypeDesc.put(124, "JustWrite");
				mapTypeDesc.put(125, "JustWrite 2.0");
				mapTypeDesc.put(126, "Lotus Documents");
				mapTypeDesc.put(127, "AMI");
				mapTypeDesc.put(128, "AMI Clip");
				mapTypeDesc.put(129, "AMI Professional");
				mapTypeDesc.put(130, "Manuscript 1.0");
				mapTypeDesc.put(131, "Manuscript 2.0");
				mapTypeDesc.put(132, "WordPro 96");
				mapTypeDesc.put(133, "WordPro 97");
				mapTypeDesc.put(134, "Microsoft Documents");
				mapTypeDesc.put(135, "Microsoft RTF");
				mapTypeDesc.put(136, "Microsoft RTF Japan");
				mapTypeDesc.put(137, "Microsoft Word");
				mapTypeDesc.put(138, "Microsoft Word 4.0 DOS");
				mapTypeDesc.put(139, "Microsoft Word 5.0 DOS");
				mapTypeDesc.put(140, "Microsoft Word 6.0 DOS");
				mapTypeDesc.put(141, "Microsoft Word 1.0");
				mapTypeDesc.put(142, "Microsoft Word 1.0 Complex");
				mapTypeDesc.put(143, "Microsoft Word 1.0 Japan");
				mapTypeDesc.put(144, "Microsoft Word 2.0");
				mapTypeDesc.put(145, "Microsoft Word 2.0 Japan");
				mapTypeDesc.put(146, "Microsoft Word 5.0 Japan");
				mapTypeDesc.put(147, "Microsoft Word 6.0");
				mapTypeDesc.put(148, "Microsoft Word 7.0");
				mapTypeDesc.put(149, "Microsoft Word 97");
				mapTypeDesc.put(150, "Microsoft Word 2000");
				mapTypeDesc.put(151, "Microsoft Word 2002");
				mapTypeDesc.put(152, "Microsoft Word 2003");
				mapTypeDesc.put(153, "Microsoft Word 2007");
				mapTypeDesc.put(154, "Encrypted Word 2007");
				mapTypeDesc.put(155, "Word Template 2007");
				mapTypeDesc.put(156, "Microsoft Pocket Word 1.0");
				mapTypeDesc.put(157, "Microsoft Pocket Word 2.0");
				mapTypeDesc.put(158, "Microsoft Word 2003 XML");
				mapTypeDesc.put(159, "Microsoft Word 12 XML");
				mapTypeDesc.put(160, "Microsoft Word (Mac)");
				mapTypeDesc.put(161, "Microsoft Word 3 (Mac)");
				mapTypeDesc.put(162, "Microsoft Word 4 (Mac)");
				mapTypeDesc.put(163, "Microsoft Word 4 Complex (Mac)");
				mapTypeDesc.put(164, "Microsoft Word 5 (Mac)");
				mapTypeDesc.put(165, "Microsoft Word 6 (Mac)");
				mapTypeDesc.put(166, "Microsoft Word 97 (Mac)");
				mapTypeDesc.put(167, "Microsoft Wordpad");
				mapTypeDesc.put(168, "Microsoft Works Documents");
				mapTypeDesc.put(169, "Microsoft Works Doc 1.0");
				mapTypeDesc.put(170, "Microsoft Works Doc 2.0");
				mapTypeDesc.put(171, "Microsoft Works Doc 2.0 (Win)");
				mapTypeDesc.put(172, "Microsoft Works Doc 3.0");
				mapTypeDesc.put(173, "Microsoft Works Doc 4.0");
				mapTypeDesc.put(174, "Microsoft Works Doc 5.0");
				mapTypeDesc.put(175, "Microsoft Works Doc 2.0 (Mac)");
				mapTypeDesc.put(176, "Microsoft Write");
				mapTypeDesc.put(177, "Microsoft XPS");
				mapTypeDesc.put(178, "SearchML Documents");
				mapTypeDesc.put(179, "SearchML 1.0");
				mapTypeDesc.put(180, "SearchML 2.0");
				mapTypeDesc.put(181, "SearchML 3.0");
				mapTypeDesc.put(182, "SearchML 3.1");
				mapTypeDesc.put(183, "StarOffice and OpenOffice Writer");
				mapTypeDesc.put(184, "StarOffice 5.2 Writer");
				mapTypeDesc.put(185, "StarOffice 6 / OpenOffice 1 Writer");
				mapTypeDesc.put(186, "StarOffice 8 / OpenOffice 2/3 Writer / OpenDocument Text");
				mapTypeDesc.put(187, "WML");
				mapTypeDesc.put(188, "WML document");
				mapTypeDesc.put(189, "Binary WML");
				mapTypeDesc.put(190, "Chinese (Big5) WML");
				mapTypeDesc.put(191, "Chinese (EUC) WML");
				mapTypeDesc.put(192, "Chinese (GB) WML");
				mapTypeDesc.put(193, "CSS WML");
				mapTypeDesc.put(194, "Cyrillic (ANSI 1251) WML");
				mapTypeDesc.put(195, "Cyrillic (KOI8-R) WML");
				mapTypeDesc.put(196, "Japanese (JIS) WML");
				mapTypeDesc.put(197, "Japanese (ShiftJIS) WML");
				mapTypeDesc.put(198, "Japanese (EUC) WML");
				mapTypeDesc.put(199, "Korean (Hangul) WML");
				mapTypeDesc.put(200, "Central European WML");
				mapTypeDesc.put(201, "WordPerfect");
				mapTypeDesc.put(202, "WordPerfect 4.2");
				mapTypeDesc.put(203, "WordPerfect 5.0");
				mapTypeDesc.put(204, "WordPerfect 5.0 Europe");
				mapTypeDesc.put(205, "WordPerfect 5.1");
				mapTypeDesc.put(206, "WordPerfect 5.1 Japan");
				mapTypeDesc.put(207, "WordPerfect 6.0");
				mapTypeDesc.put(208, "WordPerfect 6.0 Europe");
				mapTypeDesc.put(209, "WordPerfect 6.1");
				mapTypeDesc.put(210, "WordPerfect 7.0");
				mapTypeDesc.put(211, "WordPerfect 8.0");
				mapTypeDesc.put(212, "WordPerfect 1 (Mac)");
				mapTypeDesc.put(213, "WordPerfect 2 (Mac)");
				mapTypeDesc.put(214, "WordPerfect 3 (Mac)");
				mapTypeDesc.put(215, "WordPerfect Encrypted");
				mapTypeDesc.put(216, "WordPerfect/Novell Unknown Format");
				mapTypeDesc.put(217, "WordPerfect 5 Asia");
				mapTypeDesc.put(218, "WordPerfect 6.1 enhanced");
				mapTypeDesc.put(219, "WordPerfect 7 enhanced");
				mapTypeDesc.put(220, "WordPerfect 8 enhanced");
				mapTypeDesc.put(221, "WordPerfect 9 enhanced");
				mapTypeDesc.put(222, "WordPerfect 9");
				mapTypeDesc.put(223, "WordPerfect 6 Asia enhanced");
				mapTypeDesc.put(224, "WordPerfect 6 Asia");
				mapTypeDesc.put(225, "WordPerfect 6.1 Asia enhanced");
				mapTypeDesc.put(226, "WordPerfect 6.1 Asia");
				mapTypeDesc.put(227, "WordPerfect 7 Asia enhanced");
				mapTypeDesc.put(228, "WordPerfect 7 Asia");
				mapTypeDesc.put(229, "WordPerfect 8 Asia enhanced");
				mapTypeDesc.put(230, "WordPerfect 8 Asia");
				mapTypeDesc.put(231, "WordPerfect 2 Mac enhanced");
				mapTypeDesc.put(232, "WordPerfect 2.1 Mac enhanced");
				mapTypeDesc.put(233, "WordPerfect 2.1 Mac");
				mapTypeDesc.put(234, "WordPerfect 3 Mac enhanced");
				mapTypeDesc.put(235, "WordPerfect 3.5 Mac enhanced");
				mapTypeDesc.put(236, "WordPerfect 3.5 Mac");
				mapTypeDesc.put(237, "WordPerfect 3.5e Mac enhanced");
				mapTypeDesc.put(238, "WordPerfect 3.5e Mac");
				mapTypeDesc.put(239, "WordPerfect Supplementary Files");
				mapTypeDesc.put(240, "WordPerfect DrawPerfect");
				mapTypeDesc.put(241, "WordPerfect Macro");
				mapTypeDesc.put(242, "WordPerfect Help");
				mapTypeDesc.put(243, "WordPerfect Keyboard");
				mapTypeDesc.put(244, "WordPerfect VAX Keyboard");
				mapTypeDesc.put(245, "WordPerfect Dictionary");
				mapTypeDesc.put(246, "WordPerfect Thesaurus");
				mapTypeDesc.put(247, "WordPerfect Block");
				mapTypeDesc.put(248, "WordPerfect Rectblock");
				mapTypeDesc.put(249, "WordPerfect Colblock");
				mapTypeDesc.put(250, "WordPerfect Printer");
				mapTypeDesc.put(251, "WordPerfect Setup");
				mapTypeDesc.put(252, "WordPerfect Display");
				mapTypeDesc.put(253, "WordPerfect Overlay");
				mapTypeDesc.put(254, "WordPerfect Hyphen Code");
				mapTypeDesc.put(255, "WordPerfect Hyphen Data");
				mapTypeDesc.put(256, "WordPerfect Macro Resource");
				mapTypeDesc.put(257, "WordPerfect Graphic Driver");
				mapTypeDesc.put(258, "WordPerfect Hyphen Lex");
				mapTypeDesc.put(259, "WordPerfect QCodes");
				mapTypeDesc.put(260, "WordPerfect Spellchecker List");
				mapTypeDesc.put(261, "WordPerfect Equation Resource");
				mapTypeDesc.put(262, "WordPerfect VAX Setup");
				mapTypeDesc.put(263, "WordPerfect Spellchecker Rules");
				mapTypeDesc.put(264, "WordPerfect Dictionary Rules");
				mapTypeDesc.put(265, "WordPerfect Rhyme Words");
				mapTypeDesc.put(266, "WordPerfect Rhyme Pronunciation");
				mapTypeDesc.put(267, "WordPerfect Install Options");
				mapTypeDesc.put(268, "WordPerfect Mouse");
				mapTypeDesc.put(269, "WordPerfect UNIX Setup");
				mapTypeDesc.put(270, "WordPerfect 42 VAX");
				mapTypeDesc.put(271, "WordPerfect External Spellchecker Code");
				mapTypeDesc.put(272, "WordPerfect External Spellchecker Dictionary");
				mapTypeDesc.put(273, "WordPerfect MacSoft Graphics");
				mapTypeDesc.put(274, "WordPerfect Character Map");
				mapTypeDesc.put(275, "WordPerfect App Lib");
				mapTypeDesc.put(276, "WordPerfect Shell");
				mapTypeDesc.put(277, "WordPerfect Notebook");
				mapTypeDesc.put(278, "WordPerfect Calculator");
				mapTypeDesc.put(279, "WordPerfect File Manager");
				mapTypeDesc.put(280, "WordPerfect Calendar");
				mapTypeDesc.put(281, "WordPerfect Editor");
				mapTypeDesc.put(282, "WordPerfect Macro Editor");
				mapTypeDesc.put(283, "WordPerfect PlanPerfect");
				mapTypeDesc.put(284, "WordPerfect DataPerfect");
				mapTypeDesc.put(285, "WordPerfect Mail");
				mapTypeDesc.put(286, "WordPerfect PTR");
				mapTypeDesc.put(287, "WordPerfect Scheduler");
				mapTypeDesc.put(288, "WordPerfect Office");
				mapTypeDesc.put(289, "Yahoo IM");
				mapTypeDesc.put(290, "Other Documents");
				mapTypeDesc.put(291, "Arehangeul");
				mapTypeDesc.put(292, "CEO");
				mapTypeDesc.put(293, "CEO Word");
				mapTypeDesc.put(294, "CEO Write");
				mapTypeDesc.put(295, "DEC WP");
				mapTypeDesc.put(296, "DEC WPS");
				mapTypeDesc.put(297, "DEC WPS Plus");
				mapTypeDesc.put(298, "Digital WPS Plus");
				mapTypeDesc.put(299, "DisplayWrite");
				mapTypeDesc.put(300, "DisplayWrite 2");
				mapTypeDesc.put(301, "DisplayWrite 4.0");
				mapTypeDesc.put(302, "DisplayWrite 5.0");
				mapTypeDesc.put(303, "EBCDIC");
				mapTypeDesc.put(304, "Enable Documents");
				mapTypeDesc.put(305, "Enable 3.0");
				mapTypeDesc.put(306, "Enable 4.0");
				mapTypeDesc.put(307, "First Choice Docs");
				mapTypeDesc.put(308, "First Choice");
				mapTypeDesc.put(309, "First Choice 3.0");
				mapTypeDesc.put(310, "FTDF");
				mapTypeDesc.put(311, "Hana");
				mapTypeDesc.put(312, "HDML");
				mapTypeDesc.put(313, "Interleaf 6");
				mapTypeDesc.put(314, "Interleaf Japan");
				mapTypeDesc.put(315, "Legacy Docs");
				mapTypeDesc.put(316, "Legacy");
				mapTypeDesc.put(317, "Legacy Clip");
				mapTypeDesc.put(318, "MacWrite II");
				mapTypeDesc.put(319, "MASS11");
				mapTypeDesc.put(320, "MASS11 PC");
				mapTypeDesc.put(321, "MASS11 VAX");
				mapTypeDesc.put(322, "Matsu 4");
				mapTypeDesc.put(323, "Matsu 5");
				mapTypeDesc.put(324, "MultiMate");
				mapTypeDesc.put(325, "MultiMate 3.6");
				mapTypeDesc.put(326, "MultiMate 4.0");
				mapTypeDesc.put(327, "MultiMate Advanced");
				mapTypeDesc.put(328, "MultiMate Note");
				mapTypeDesc.put(329, "Navy DIF");
				mapTypeDesc.put(330, "Novell PerfectWorks");
				mapTypeDesc.put(331, "Office Writer");
				mapTypeDesc.put(332, "P1 Japan");
				mapTypeDesc.put(333, "PageML");
				mapTypeDesc.put(334, "PC-File Letter");
				mapTypeDesc.put(335, "PFS:Write");
				mapTypeDesc.put(336, "PFS:Write A");
				mapTypeDesc.put(337, "PFS:Write B");
				mapTypeDesc.put(338, "Professional Write");
				mapTypeDesc.put(339, "Professional Write 1.0");
				mapTypeDesc.put(340, "Professional Write 2.0");
				mapTypeDesc.put(341, "Professional Write Plus");
				mapTypeDesc.put(342, "Professional Write Plus Clip");
				mapTypeDesc.put(343, "Professional Write");
				mapTypeDesc.put(344, "Q&A Write Documents");
				mapTypeDesc.put(345, "Q&A Write");
				mapTypeDesc.put(346, "Q&A Write 3.0");
				mapTypeDesc.put(347, "Rainbow");
				mapTypeDesc.put(348, "Samna Word");
				mapTypeDesc.put(349, "Search text");
				mapTypeDesc.put(350, "Signature");
				mapTypeDesc.put(351, "SmartWare II");
				mapTypeDesc.put(352, "Sprint");
				mapTypeDesc.put(353, "Total Word");
				mapTypeDesc.put(354, "TNEF");
				mapTypeDesc.put(355, "vCalendar");
				mapTypeDesc.put(356, "vCard");
				mapTypeDesc.put(357, "Volkswriter");
				mapTypeDesc.put(358, "Wang PC");
				mapTypeDesc.put(359, "Wang IWP");
				mapTypeDesc.put(360, "WordMARC");
				mapTypeDesc.put(361, "WordStar");
				mapTypeDesc.put(362, "WordStar 2000");
				mapTypeDesc.put(363, "WordStar 4.0");
				mapTypeDesc.put(364, "WordStar 5.0");
				mapTypeDesc.put(365, "WordStar 5.5");
				mapTypeDesc.put(366, "WordStar 6.0");
				mapTypeDesc.put(367, "WordStar 7.0");
				mapTypeDesc.put(368, "WordStar Win");
				mapTypeDesc.put(369, "WWRITE");
				mapTypeDesc.put(370, "WWRITE - Chinese BIG5");
				mapTypeDesc.put(371, "WWRITE - Chinese GB");
				mapTypeDesc.put(372, "WWRITE - Hangul");
				mapTypeDesc.put(373, "WWRITE - Japan SJIS");
				mapTypeDesc.put(374, "XyWrite");
				mapTypeDesc.put(375, "Lotus Spreadsheets");
				mapTypeDesc.put(376, "Lotus Symphony");
				mapTypeDesc.put(377, "Lotus 123 1.0");
				mapTypeDesc.put(378, "Lotus 123 2.0");
				mapTypeDesc.put(379, "Lotus 123 2.0 OS2");
				mapTypeDesc.put(380, "Lotus 123 2.0 OS2 Charts");
				mapTypeDesc.put(381, "Lotus 123 3.0");
				mapTypeDesc.put(382, "Lotus 123 4.0");
				mapTypeDesc.put(383, "Lotus 123 6.0");
				mapTypeDesc.put(384, "Lotus 123 9.0");
				mapTypeDesc.put(385, "Lotus 123-J");
				mapTypeDesc.put(386, "Lotus 123 2.0 (FRM)");
				mapTypeDesc.put(387, "Lotus 123");
				mapTypeDesc.put(388, "Lotus 123 97");
				mapTypeDesc.put(389, "Lotus 123 SEAL");
				mapTypeDesc.put(390, "Lotus 123 (corrupt)");
				mapTypeDesc.put(391, "Lotus 123 3.0 (corrupt)");
				mapTypeDesc.put(392, "Lotus 123 4.0 (corrupt)");
				mapTypeDesc.put(393, "Lotus 123 97 (corrupt)");
				mapTypeDesc.put(394, "Lotus 123-J (corrupt)");
				mapTypeDesc.put(395, "Lotus 123 2.0 (FRM) (corrupt)");
				mapTypeDesc.put(396, "Microsoft Spreadsheets");
				mapTypeDesc.put(397, "Excel Spreadsheets");
				mapTypeDesc.put(398, "Excel 2.0");
				mapTypeDesc.put(399, "Excel 3.0");
				mapTypeDesc.put(400, "Excel 3.0 Workbook");
				mapTypeDesc.put(401, "Excel 4.0");
				mapTypeDesc.put(402, "Excel 4.0 Workbook");
				mapTypeDesc.put(403, "Excel 5.0");
				mapTypeDesc.put(404, "Excel 97");
				mapTypeDesc.put(405, "Excel 2000");
				mapTypeDesc.put(406, "Excel 2002");
				mapTypeDesc.put(407, "Excel 2003");
				mapTypeDesc.put(408, "Excel 2007");
				mapTypeDesc.put(409, "Encrypted Excel 2007");
				mapTypeDesc.put(410, "Excel 95");
				mapTypeDesc.put(411, "Excel Mac 4");
				mapTypeDesc.put(412, "Excel Mac 4 Workbook");
				mapTypeDesc.put(413, "Excel Mac 4 WB");
				mapTypeDesc.put(414, "Excel Mac 5");
				mapTypeDesc.put(415, "Multiplan");
				mapTypeDesc.put(416, "Microsoft Works Spreadsheets");
				mapTypeDesc.put(417, "Microsoft Works Spreadsheet 1.0");
				mapTypeDesc.put(418, "Microsoft Works Spreadsheet 3.0");
				mapTypeDesc.put(419, "Microsoft Works Spreadsheet 4.0");
				mapTypeDesc.put(420, "Microsoft Works Spreadsheet (Mac)");
				mapTypeDesc.put(421, "Quattro Pro Spreadsheets");
				mapTypeDesc.put(422, "Quattro 1");
				mapTypeDesc.put(423, "Quattro Pro 1");
				mapTypeDesc.put(424, "Quattro Pro 1 Japan");
				mapTypeDesc.put(425, "Quattro Pro 4");
				mapTypeDesc.put(426, "Quattro Pro Win");
				mapTypeDesc.put(427, "Quattro Pro 5");
				mapTypeDesc.put(428, "Quattro Pro 6");
				mapTypeDesc.put(429, "Quattro Pro 7");
				mapTypeDesc.put(430, "Quattro Pro 7 Graph");
				mapTypeDesc.put(431, "Quattro Pro 8");
				mapTypeDesc.put(432, "Quattro Pro 9");
				mapTypeDesc.put(433, "Quattro Pro 10");
				mapTypeDesc.put(434, "Quattro Pro 11");
				mapTypeDesc.put(435, "Quattro Pro 12");
				mapTypeDesc.put(436, "StarOffice and OpenOffice Calc");
				mapTypeDesc.put(437, "StarOffice 5.2 Calc");
				mapTypeDesc.put(438, "StarOffice 6 / OpenOffice 1 Calc");
				mapTypeDesc.put(439, "StarOffice 8 / OpenOffice 2/3 Calc / OpenDocument Spreadsheet");
				mapTypeDesc.put(440, "Other Spreadsheets");
				mapTypeDesc.put(441, "CEO Spreadsheet");
				mapTypeDesc.put(442, "Enable Spreadsheet");
				mapTypeDesc.put(443, "First Choice Spreadsheet");
				mapTypeDesc.put(444, "Mosaic Twin");
				mapTypeDesc.put(445, "Novell Perfect");
				mapTypeDesc.put(446, "PFS:Professional Plan");
				mapTypeDesc.put(447, "SmartWare II Spreadsheet");
				mapTypeDesc.put(448, "SuperCalc 5");
				mapTypeDesc.put(449, "VP Planner 3D");
				mapTypeDesc.put(450, "Generic WKS");
				mapTypeDesc.put(451, "dBASE Databases");
				mapTypeDesc.put(452, "dBASE 3");
				mapTypeDesc.put(453, "dBASE 4");
				mapTypeDesc.put(454, "dBase");
				mapTypeDesc.put(455, "dBase II");
				mapTypeDesc.put(456, "NSF 6");
				mapTypeDesc.put(457, "Microsoft Databases");
				mapTypeDesc.put(458, "Access Databases");
				mapTypeDesc.put(459, "Access 1.0");
				mapTypeDesc.put(460, "Access 7.0");
				mapTypeDesc.put(461, "Access 2.0");
				mapTypeDesc.put(462, "ESE Database");
				mapTypeDesc.put(463, "ESE Database Table");
				mapTypeDesc.put(464, "ESE Database Record");
				mapTypeDesc.put(465, "ESE Database Field");
				mapTypeDesc.put(466, "Microsoft Project");
				mapTypeDesc.put(467, "Microsoft Project 98");
				mapTypeDesc.put(468, "Microsoft Project 2000");
				mapTypeDesc.put(469, "Microsoft Project 2002");
				mapTypeDesc.put(470, "Microsoft Works Databases");
				mapTypeDesc.put(471, "Microsoft Works Databases (DOS)");
				mapTypeDesc.put(472, "Microsoft Works Databases (Win)");
				mapTypeDesc.put(473, "Microsoft Works Databases 3.0");
				mapTypeDesc.put(474, "Microsoft Works Databases 4.0");
				mapTypeDesc.put(475, "Microsoft Works Databases (Mac)");
				mapTypeDesc.put(476, "Microsoft Money");
				mapTypeDesc.put(477, "Microsoft Money 1");
				mapTypeDesc.put(478, "Microsoft Money 2");
				mapTypeDesc.put(479, "Microsoft Money 3");
				mapTypeDesc.put(480, "Microsoft Money 4");
				mapTypeDesc.put(481, "Microsoft Money 5");
				mapTypeDesc.put(482, "Active Directory Database File");
				mapTypeDesc.put(483, "Paradox Databases");
				mapTypeDesc.put(484, "Paradox  3.0");
				mapTypeDesc.put(485, "Paradox 3.5");
				mapTypeDesc.put(486, "Paradox 4.0");
				mapTypeDesc.put(487, "Paradox (Unknown Version)");
				mapTypeDesc.put(488, "R:Base Databases");
				mapTypeDesc.put(489, "Personal R:Base");
				mapTypeDesc.put(490, "Personal R:Base 3.0");
				mapTypeDesc.put(491, "R:Base 5000");
				mapTypeDesc.put(492, "R:Base System V");
				mapTypeDesc.put(493, "Other Databases");
				mapTypeDesc.put(494, "DataEase");
				mapTypeDesc.put(495, "CEO Database");
				mapTypeDesc.put(496, "First Choice Database");
				mapTypeDesc.put(497, "Framework");
				mapTypeDesc.put(498, "Reflex");
				mapTypeDesc.put(499, "Q&A Database");
				mapTypeDesc.put(500, "SmartWare II Database");
				mapTypeDesc.put(501, "Approach 97");
				mapTypeDesc.put(502, "Approach 96");
				mapTypeDesc.put(503, "FileMaker Pro 3.0");
				mapTypeDesc.put(504, "FileMaker Pro 5.0");
				mapTypeDesc.put(505, "QuickBooks");
				mapTypeDesc.put(506, "QuickBooks 2");
				mapTypeDesc.put(507, "QuickBooks 3.1");
				mapTypeDesc.put(508, "QuickBooks 5");
				mapTypeDesc.put(509, "QuickBooks 6");
				mapTypeDesc.put(510, "QuickBooks 99");
				mapTypeDesc.put(511, "QuickBooks 2000");
				mapTypeDesc.put(512, "Quicken");
				mapTypeDesc.put(513, "Quicken 4");
				mapTypeDesc.put(514, "Quicken 5");
				mapTypeDesc.put(515, "Quicken 6");
				mapTypeDesc.put(516, "Quicken 98");
				mapTypeDesc.put(517, "Quicken 99");
				mapTypeDesc.put(518, "Quicken 2000");
				mapTypeDesc.put(519, "Quicken 2001");
				mapTypeDesc.put(520, "Corel Presentations Files");
				mapTypeDesc.put(521, "Corel Presentations");
				mapTypeDesc.put(522, "Corel Presentations 7.0");
				mapTypeDesc.put(523, "Harvard Graphics");
				mapTypeDesc.put(524, "Harvard Graphics 2.0");
				mapTypeDesc.put(525, "Harvard Graphics 3.0");
				mapTypeDesc.put(526, "Harvard Graphics 3.0 PRS");
				mapTypeDesc.put(527, "Harvard Graphics Win");
				mapTypeDesc.put(528, "Lotus Freelance Files");
				mapTypeDesc.put(529, "Lotus Freelance");
				mapTypeDesc.put(530, "Lotus Freelance 3.0");
				mapTypeDesc.put(531, "PowerPoint");
				mapTypeDesc.put(532, "PowerPoint 2.0");
				mapTypeDesc.put(533, "PowerPoint 3.0");
				mapTypeDesc.put(534, "PowerPoint 4.0");
				mapTypeDesc.put(535, "PowerPoint 4.0 Ext");
				mapTypeDesc.put(536, "PowerPoint 7.0");
				mapTypeDesc.put(537, "PowerPoint 95/97");
				mapTypeDesc.put(538, "PowerPoint 97");
				mapTypeDesc.put(539, "PowerPoint 2000");
				mapTypeDesc.put(540, "PowerPoint 2007");
				mapTypeDesc.put(541, "Encrypted PowerPoint 2007");
				mapTypeDesc.put(542, "PowerPoint 3.0 (Mac)");
				mapTypeDesc.put(543, "PowerPoint 3.0 (Mac) B");
				mapTypeDesc.put(544, "PowerPoint 4.0 (Mac)");
				mapTypeDesc.put(545, "PowerPoint 4.0 (Mac) B");
				mapTypeDesc.put(546, "PowerPoint 4.0 (Mac) Ext");
				mapTypeDesc.put(547, "StarOffice and OpenOffice Impress");
				mapTypeDesc.put(548, "StarOffice 5.2 Impress");
				mapTypeDesc.put(549, "StarOffice 6 / OpenOffice 1 Impress");
				mapTypeDesc.put(550, "StarOffice 8 / OpenOffice 2/3 Impress / OpenDocument Presentation");
				mapTypeDesc.put(551, "Raster Graphics");
				mapTypeDesc.put(552, "Adobe Graphics");
				mapTypeDesc.put(553, "Adobe FrameMaker Graphics");
				mapTypeDesc.put(554, "Adobe Photoshop");
				mapTypeDesc.put(555, "Ami Draw");
				mapTypeDesc.put(556, "Bitmap");
				mapTypeDesc.put(557, "Bitmap Win 98/2000");
				mapTypeDesc.put(558, "CALS Raster");
				mapTypeDesc.put(559, "Candy 4");
				mapTypeDesc.put(560, "Corel Graphics");
				mapTypeDesc.put(561, "Corel Draw Clipart");
				mapTypeDesc.put(562, "Paintshop Pro");
				mapTypeDesc.put(563, "eFax");
				mapTypeDesc.put(564, "Export Image");
				mapTypeDesc.put(565, "GEM Paint");
				mapTypeDesc.put(566, "GIF");
				mapTypeDesc.put(567, "HP Gallery");
				mapTypeDesc.put(568, "IBM GDF");
				mapTypeDesc.put(569, "IBM PIF");
				mapTypeDesc.put(570, "IGES");
				mapTypeDesc.put(571, "JBIG2 Bitmap");
				mapTypeDesc.put(572, "JPEG");
				mapTypeDesc.put(573, "JPEG EXIF");
				mapTypeDesc.put(574, "AOL Art");
				mapTypeDesc.put(575, "ANI file");
				mapTypeDesc.put(576, "IFF ANIM");
				mapTypeDesc.put(577, "Windows Animated Cursor ");
				mapTypeDesc.put(578, "Animatic Film");
				mapTypeDesc.put(579, "Computer Eyes");
				mapTypeDesc.put(580, "Intel Digital Video");
				mapTypeDesc.put(581, "MNG");
				mapTypeDesc.put(582, "JNG");
				mapTypeDesc.put(583, "PC Paint");
				mapTypeDesc.put(584, "CyberPaint");
				mapTypeDesc.put(585, "PNTG");
				mapTypeDesc.put(586, "Autodesk ANI");
				mapTypeDesc.put(587, "Autodesk 3D");
				mapTypeDesc.put(588, "Kodak Graphics");
				mapTypeDesc.put(589, "Flash Pix");
				mapTypeDesc.put(590, "Photo CD");
				mapTypeDesc.put(591, "Mac Graphics");
				mapTypeDesc.put(592, "PICT1");
				mapTypeDesc.put(593, "PICT2");
				mapTypeDesc.put(594, "MacPaint");
				mapTypeDesc.put(595, "MIFF Graphics");
				mapTypeDesc.put(596, "Multipage PCX");
				mapTypeDesc.put(597, "OS/2 Bitmap");
				mapTypeDesc.put(598, "OS/2 Bitmap V2");
				mapTypeDesc.put(599, "OS/2 Warp Bitmap");
				mapTypeDesc.put(600, "PC Paintbrush");
				mapTypeDesc.put(601, "PNG");
				mapTypeDesc.put(602, "Portable Bitmap");
				mapTypeDesc.put(603, "Portable Graymap");
				mapTypeDesc.put(604, "Portable Pixmap (PPM)");
				mapTypeDesc.put(605, "Progressive JPEG");
				mapTypeDesc.put(606, "StarOffice and OpenOffice Draw");
				mapTypeDesc.put(607, "StarOffice 6 / OpenOffice 1 Draw");
				mapTypeDesc.put(608, "StarOffice 8 / OpenOffice 2/3 Draw / OpenDocument Graphic");
				mapTypeDesc.put(609, "Sun Raster");
				mapTypeDesc.put(610, "Targa");
				mapTypeDesc.put(611, "Tiff");
				mapTypeDesc.put(612, "TIFF CCITT Group 3");
				mapTypeDesc.put(613, "Windows Cursor");
				mapTypeDesc.put(614, "Windows Icon");
				mapTypeDesc.put(615, "Wireless Bitmap");
				mapTypeDesc.put(616, "WordPerfect Graphics");
				mapTypeDesc.put(617, "WordPerfect Graphics 1.0");
				mapTypeDesc.put(618, "WordPerfect Graphics 2.0");
				mapTypeDesc.put(619, "WordPerfect Graphics 7.0");
				mapTypeDesc.put(620, "WordPerfect Graphics 10.0");
				mapTypeDesc.put(621, "X-Windows Graphics");
				mapTypeDesc.put(622, "Bitmap (XBM)");
				mapTypeDesc.put(623, "Dump (XWD)");
				mapTypeDesc.put(624, "Pixmap (XPM)");
				mapTypeDesc.put(625, "Vector Graphics");
				mapTypeDesc.put(626, "Adobe Illustrator");
				mapTypeDesc.put(627, "Adobe Illustrator 9.0");
				mapTypeDesc.put(628, "AutoCAD");
				mapTypeDesc.put(629, "AutoCAD DXB");
				mapTypeDesc.put(630, "AutoCAD (DXF) A");
				mapTypeDesc.put(631, "AutoCAD (DXF) B");
				mapTypeDesc.put(632, "AutoCAD (DWG)");
				mapTypeDesc.put(633, "AutoCAD 2.5");
				mapTypeDesc.put(634, "AutoCAD 2.6");
				mapTypeDesc.put(635, "AutoCAD 9");
				mapTypeDesc.put(636, "AutoCAD 10");
				mapTypeDesc.put(637, "AutoCAD 12");
				mapTypeDesc.put(638, "AutoCAD 13");
				mapTypeDesc.put(639, "AutoCAD 14");
				mapTypeDesc.put(640, "AutoCAD 2000");
				mapTypeDesc.put(641, "AutoCAD 2004");
				mapTypeDesc.put(642, "AutoCAD 2007");
				mapTypeDesc.put(643, "AutoCAD (Unknown Version)");
				mapTypeDesc.put(644, "AUTOSHADE");
				mapTypeDesc.put(645, "Bentley DGN");
				mapTypeDesc.put(646, "Computer Graphics Metafile");
				mapTypeDesc.put(647, "Corel Draw");
				mapTypeDesc.put(648, "Corel Draw 2.0");
				mapTypeDesc.put(649, "Corel Draw 3.0");
				mapTypeDesc.put(650, "Corel Draw 4.0");
				mapTypeDesc.put(651, "Corel Draw 5.0");
				mapTypeDesc.put(652, "Corel Draw 6.0");
				mapTypeDesc.put(653, "Corel Draw 7.0");
				mapTypeDesc.put(654, "Corel Draw 8.0");
				mapTypeDesc.put(655, "Corel Draw 9.0");
				mapTypeDesc.put(656, "Corel Draw 10.0");
				mapTypeDesc.put(657, "Corel Draw 11.0");
				mapTypeDesc.put(658, "Excel Charts");
				mapTypeDesc.put(659, "Excel 2.x Chart");
				mapTypeDesc.put(660, "Excel 3.0 Chart");
				mapTypeDesc.put(661, "Excel 4.0 Chart");
				mapTypeDesc.put(662, "Excel 5.0/7.0 Chart");
				mapTypeDesc.put(663, "Hanako 1.x");
				mapTypeDesc.put(664, "Hanako 2.x");
				mapTypeDesc.put(665, "Hewlett Packard Graphics");
				mapTypeDesc.put(666, "Picture File Format");
				mapTypeDesc.put(667, "Micrografx Graphics");
				mapTypeDesc.put(668, "Draw");
				mapTypeDesc.put(669, "Designer (DRW)");
				mapTypeDesc.put(670, "Designer (DSF)");
				mapTypeDesc.put(671, "OS/2 Metafiles");
				mapTypeDesc.put(672, "Postscript");
				mapTypeDesc.put(673, "QuarkXPress");
				mapTypeDesc.put(674, "QuarkXPress 3.0 Mac");
				mapTypeDesc.put(675, "QuarkXPress 3.1 Mac");
				mapTypeDesc.put(676, "QuarkXPress 3.2 Mac");
				mapTypeDesc.put(677, "QuarkXPress 3.3 Mac");
				mapTypeDesc.put(678, "QuarkXPress 4.0 Mac");
				mapTypeDesc.put(679, "QuarkXPress 3.3 Win");
				mapTypeDesc.put(680, "QuarkXPress 4.0 Win");
				mapTypeDesc.put(681, "QuarkXPress 5.0 Win");
				mapTypeDesc.put(682, "StarView Metafile");
				mapTypeDesc.put(683, "Visio");
				mapTypeDesc.put(684, "Visio 3.0");
				mapTypeDesc.put(685, "Visio 4.0");
				mapTypeDesc.put(686, "Visio 5.0");
				mapTypeDesc.put(687, "Visio 6.0");
				mapTypeDesc.put(688, "Visio 2003");
				mapTypeDesc.put(689, "Windows Enhanced Metafile");
				mapTypeDesc.put(690, "Windows Metafile");
				mapTypeDesc.put(691, "Print Spool");
				mapTypeDesc.put(692, "Vector and Raster Graphics");
				mapTypeDesc.put(693, "EPSTIFF");
				mapTypeDesc.put(694, "Encapsulated PostScript");
				mapTypeDesc.put(695, "Graphics Environment Manager");
				mapTypeDesc.put(696, "PDF image filter");
				mapTypeDesc.put(697, "PDF Mac Bin");
				mapTypeDesc.put(698, "Audio");
				mapTypeDesc.put(699, "Director");
				mapTypeDesc.put(700, "MPEG-1 audio - Layer 1");
				mapTypeDesc.put(701, "MPEG-1 audio - Layer 2");
				mapTypeDesc.put(702, "MPEG-2 audio - Layer 1");
				mapTypeDesc.put(703, "MPEG-2 audio - Layer 2");
				mapTypeDesc.put(704, "MPEG-2 audio - Layer 3");
				mapTypeDesc.put(705, "Midi");
				mapTypeDesc.put(706, "MP3 ID3v1");
				mapTypeDesc.put(707, "MP3 ID3v2");
				mapTypeDesc.put(708, "MP3 w/o metadata");
				mapTypeDesc.put(709, "Non-MP3 ID3v1");
				mapTypeDesc.put(710, "Non-MP3 ID3v2");
				mapTypeDesc.put(711, "Riff Wave");
				mapTypeDesc.put(712, "AIFF");
				mapTypeDesc.put(713, "IFF SMUS");
				mapTypeDesc.put(714, "IFF 8SVX");
				mapTypeDesc.put(715, "iPod QuickTime");
				mapTypeDesc.put(716, "Windows Media");
				mapTypeDesc.put(717, "MPEG 2.5 Audio");
				mapTypeDesc.put(718, "Video");
				mapTypeDesc.put(719, "Flash");
				mapTypeDesc.put(720, "QuickTime");
				mapTypeDesc.put(721, "Riff Avi");
				mapTypeDesc.put(722, "MPEG 1.0 Video");
				mapTypeDesc.put(723, "MPEG 2.0 Video");
				mapTypeDesc.put(724, "Arc");
				mapTypeDesc.put(725, "Binder");
				mapTypeDesc.put(726, "MS Cabinet");
				mapTypeDesc.put(727, "GZip INSO");
				mapTypeDesc.put(728, "GZip");
				mapTypeDesc.put(729, "LZH");
				mapTypeDesc.put(730, "LZH SFX");
				mapTypeDesc.put(731, "Rar");
				mapTypeDesc.put(732, "StuffIt");
				mapTypeDesc.put(733, "Tar INSO");
				mapTypeDesc.put(734, "Tar");
				mapTypeDesc.put(735, "Zip INSO");
				mapTypeDesc.put(736, "Zip Exe");
				mapTypeDesc.put(737, "Zip");
				mapTypeDesc.put(738, "BZIP2");
				mapTypeDesc.put(739, "Norton SecretStuff");
				mapTypeDesc.put(740, "ARJ");
				mapTypeDesc.put(741, "RAR");
				mapTypeDesc.put(742, "Placeholder");
				mapTypeDesc.put(743, "Folder (unused)");
				mapTypeDesc.put(744, "Folder");
				mapTypeDesc.put(745, "Message");
				mapTypeDesc.put(746, "Email Message");
				mapTypeDesc.put(747, "Email Folder");
				mapTypeDesc.put(748, "Appointment");
				mapTypeDesc.put(749, "Contact");
				mapTypeDesc.put(750, "Journal");
				mapTypeDesc.put(751, "Note");
				mapTypeDesc.put(752, "Task");
				mapTypeDesc.put(753, "Distribution List");
				mapTypeDesc.put(754, "Email Objects");
				mapTypeDesc.put(755, "MIME");
				mapTypeDesc.put(756, "MIME Files");
				mapTypeDesc.put(757, "MIME Email Files");
				mapTypeDesc.put(758, "MIME News Files");
				mapTypeDesc.put(759, "MIME Outlook Email Files");
				mapTypeDesc.put(760, "MIME Outlook News Files");
				mapTypeDesc.put(761, "MIME HTML");
				mapTypeDesc.put(762, "Outlook MSG");
				mapTypeDesc.put(763, "Outlook PST INSO");
				mapTypeDesc.put(764, "Outlook PAB");
				mapTypeDesc.put(765, "PST 2003");
				mapTypeDesc.put(766, "Outlook PST");
				mapTypeDesc.put(767, "PSTF");
				mapTypeDesc.put(768, "Outlook Form Template");
				mapTypeDesc.put(769, "Outlook Express DBX");
				mapTypeDesc.put(770, "Text Internet Email");
				mapTypeDesc.put(771, "AOL Email Archive");
				mapTypeDesc.put(772, "Text Email");
				mapTypeDesc.put(773, "Mailbox");
				mapTypeDesc.put(774, "Microsoft Outlook");
				mapTypeDesc.put(775, "Com");
				mapTypeDesc.put(776, "Exe");
				mapTypeDesc.put(777, "Java Class");
				mapTypeDesc.put(778, "Paradox Script");
				mapTypeDesc.put(779, "Unpartitioned Space");
				mapTypeDesc.put(780, "File System Slack");
				mapTypeDesc.put(781, "Slack Space");
				mapTypeDesc.put(782, "Envoy");
				mapTypeDesc.put(783, "Envoy 7");
				mapTypeDesc.put(784, "MBox");
				mapTypeDesc.put(785, "Quick Finder");
				mapTypeDesc.put(786, "UnixComp");
				mapTypeDesc.put(787, "Win Clip file");
				mapTypeDesc.put(788, "ICF");
				mapTypeDesc.put(789, "Microsoft Escher");
				mapTypeDesc.put(790, "Plugin");
				mapTypeDesc.put(791, "Snapshot BMP");
				mapTypeDesc.put(792, "Snapshot TXT");
				mapTypeDesc.put(793, "WP IN Forms");
				mapTypeDesc.put(794, "Ami internal snap shot");
				mapTypeDesc.put(795, "Macintosh PICT");
				mapTypeDesc.put(796, "Word internal BMP");
				mapTypeDesc.put(797, "Word internal metafile");
				mapTypeDesc.put(798, "Word 6 internal metafile");
				mapTypeDesc.put(799, "Word internal snap shoot");
				mapTypeDesc.put(800, "PerfectWorks embedded");
				mapTypeDesc.put(801, "WordPerfect internal WPG");
				mapTypeDesc.put(802, "GDSF Embedded BMP");
				mapTypeDesc.put(803, "Excel embedded BMP");
				mapTypeDesc.put(804, "Interleaf embedded B&W BMP");
				mapTypeDesc.put(805, "Interleaf embedded Color BMP");
				mapTypeDesc.put(806, "PICT embedded BMP");
				mapTypeDesc.put(807, "WKS embedded BMP");
				mapTypeDesc.put(808, "WPG1 embedded BMP");
				mapTypeDesc.put(809, "WPG2 embedded BMP");
				mapTypeDesc.put(810, "Encrypted Unknown MS Doc");
				mapTypeDesc.put(811, "Domino XML");
				mapTypeDesc.put(812, "OLE Storage");
				mapTypeDesc.put(813, "OLE Stream");
				mapTypeDesc.put(814, "OLE Archive");
				mapTypeDesc.put(815, "OLE");
				mapTypeDesc.put(816, "Thumbs.db");
				mapTypeDesc.put(817, "Disk");
				mapTypeDesc.put(818, "Disk Image");
				mapTypeDesc.put(819, "Partition");
				mapTypeDesc.put(820, "File System");
				mapTypeDesc.put(821, "Live Folder");
				mapTypeDesc.put(822, "Generic Archive");
				mapTypeDesc.put(823, "Windows Swapfile");
				mapTypeDesc.put(824, "Windows Help");
				mapTypeDesc.put(825, "MSIE Cache Index");
				mapTypeDesc.put(826, "MSIE Cookie Index");
				mapTypeDesc.put(827, "MSIE History");
				mapTypeDesc.put(828, "Netscape History");
				mapTypeDesc.put(829, "Netscape Address Book");
				mapTypeDesc.put(830, "Netscape Database");
				mapTypeDesc.put(831, "Quake PAK");
				mapTypeDesc.put(832, "Doom WAD");
				mapTypeDesc.put(833, "Doom WAD 3");
				mapTypeDesc.put(834, "Quake BIFF v.1");
				mapTypeDesc.put(835, "Quake BIFF v.1 Complex");
				mapTypeDesc.put(836, "Quake BIFC v.1 Complex");
				mapTypeDesc.put(837, "Quake BSP");
				mapTypeDesc.put(838, "Recycle Bin Index");
				mapTypeDesc.put(839, "Netscape Cooke Index");
				mapTypeDesc.put(840, "EFS Startkey");
				mapTypeDesc.put(841, "EFS FEK Stream");
				mapTypeDesc.put(842, "VersaCheck Pro");
				mapTypeDesc.put(843, "Password List (Old)");
				mapTypeDesc.put(844, "Password List (New)");
				mapTypeDesc.put(845, "EFS Protect Files");
				mapTypeDesc.put(846, "EFS Private Key");
				mapTypeDesc.put(847, "Scheduler");
				mapTypeDesc.put(848, "Screensaver");
				mapTypeDesc.put(849, "Windows 9x Registry");
				mapTypeDesc.put(850, "Windows NT Registry");
				mapTypeDesc.put(851, "Windows Shortcut");
				mapTypeDesc.put(852, "VersaCheck Home");
				mapTypeDesc.put(853, "EFS Encrypted Files");
				mapTypeDesc.put(854, "Document Summary Information");
				mapTypeDesc.put(855, "Summary Information");
				mapTypeDesc.put(856, "Act!");
				mapTypeDesc.put(857, "Act! 1.1");
				mapTypeDesc.put(858, "Act! 2");
				mapTypeDesc.put(859, "Act! 3");
				mapTypeDesc.put(860, "Ascend");
				mapTypeDesc.put(861, "BestCrypt");
				mapTypeDesc.put(862, "BestCrypt GOST/DES");
				mapTypeDesc.put(863, "BestCrypt GOST/BFISH");
				mapTypeDesc.put(864, "BestCrypt GOST/2FISH");
				mapTypeDesc.put(865, "BestCrypt GOST/GOST");
				mapTypeDesc.put(866, "BestCrypt GOST/Unknown");
				mapTypeDesc.put(867, "BestCrypt SHA/DES");
				mapTypeDesc.put(868, "BestCrypt SHA/BFISH");
				mapTypeDesc.put(869, "BestCrypt SHA/2FISH");
				mapTypeDesc.put(870, "BestCrypt SHA/GOST");
				mapTypeDesc.put(871, "BestCrypt SHA/Unknown");
				mapTypeDesc.put(872, "BestCrypt Unknown");
				mapTypeDesc.put(873, "Lotus Organizer");
				mapTypeDesc.put(874, "Organizer 1");
				mapTypeDesc.put(875, "Organizer 2");
				mapTypeDesc.put(876, "Organizer 3");
				mapTypeDesc.put(877, "Organizer 4");
				mapTypeDesc.put(878, "PGP");
				mapTypeDesc.put(879, "PGP (Old)");
				mapTypeDesc.put(880, "PGP (New)");
				mapTypeDesc.put(881, "PGP Message");
				mapTypeDesc.put(882, "PGP Disk 4");
				mapTypeDesc.put(883, "AOL");
				mapTypeDesc.put(884, "AOL Global Org");
				mapTypeDesc.put(885, "Other AOL Files");
				mapTypeDesc.put(886, "AOL AutoComplete");
				mapTypeDesc.put(887, "AOL User History");
				mapTypeDesc.put(888, "AOL Contacts");
				mapTypeDesc.put(889, "AOL Buddy List");
				mapTypeDesc.put(890, "Palm");
				mapTypeDesc.put(891, "Palm Addressbook");
				mapTypeDesc.put(892, "Palm Datebook");
				mapTypeDesc.put(893, "Palm Todo");
				mapTypeDesc.put(894, "Palm Memo Pad");
				mapTypeDesc.put(895, "Palm Users");
				mapTypeDesc.put(896, "Palm Doc");
				mapTypeDesc.put(897, "Palm PDB");
				mapTypeDesc.put(898, "AccessData");
				mapTypeDesc.put(899, "AccessData Recovery 5.0 Status Report");
				mapTypeDesc.put(900, "AccessData Recovery 5.0 Biographical Data");
				mapTypeDesc.put(901, "AccessData Recovery 5.0 Profile Data");
				mapTypeDesc.put(902, "AccessData Recovery 5.0 Password Data");
				mapTypeDesc.put(903, "AccessData Recovery 5.0 Dictionary, v.5-8");
				mapTypeDesc.put(904, "AccessData Recovery 5.0 Dictionary, v.9+");
				mapTypeDesc.put(905, "AccessData Recovery 5.0 Biographical Dictionary");
				mapTypeDesc.put(906, "AccessData Recovery 5.0 Hard Drive Dictionary");
				mapTypeDesc.put(907, "Zero Length File");
				mapTypeDesc.put(908, "Other Unknown types");
				mapTypeDesc.put(909, "Metadata");
				mapTypeDesc.put(910, "Unallocated Space");
				mapTypeDesc.put(911, "Symlink");
				mapTypeDesc.put(912, "Alternate Data Stream");
				mapTypeDesc.put(913, "Index Allocation");
				mapTypeDesc.put(914, "Unknown");
				mapTypeDesc.put(915, "Not Yet Identified");
				mapTypeDesc.put(916, "Generic");
				mapTypeDesc.put(917, "7 bit text");
				mapTypeDesc.put(918, "ANSI 7");
				mapTypeDesc.put(919, "ANSI 8");
				mapTypeDesc.put(920, "ASCII 7");
				mapTypeDesc.put(921, "Unknown");
				mapTypeDesc.put(922, "Text");
				mapTypeDesc.put(923, "Arabic (710)");
				mapTypeDesc.put(924, "Arabic (720)");
				mapTypeDesc.put(925, "Arabic (ASMO)");
				mapTypeDesc.put(926, "Arabic (DOS)");
				mapTypeDesc.put(927, "Arabic (ISO)");
				mapTypeDesc.put(928, "Arabic (Mac)");
				mapTypeDesc.put(929, "Arabic (Win)");
				mapTypeDesc.put(930, "Baltic (ISO)");
				mapTypeDesc.put(931, "Baltic (Win)");
				mapTypeDesc.put(932, "Binary Hex Encoded Text");
				mapTypeDesc.put(933, "Binary Hex Encoded Part");
				mapTypeDesc.put(934, "Central European Text (1250)");
				mapTypeDesc.put(935, "Central European Text (DOS)");
				mapTypeDesc.put(936, "Central European Text (ISO)");
				mapTypeDesc.put(937, "Central European Text (Mac)");
				mapTypeDesc.put(938, "Central European Text (Win)");
				mapTypeDesc.put(939, "Chinese GB");
				mapTypeDesc.put(940, "Chinese BIG5");
				mapTypeDesc.put(941, "Chinese Simplified Text");
				mapTypeDesc.put(942, "Chinese Traditional Text");
				mapTypeDesc.put(943, "Cyrillic (ANSI 1251)");
				mapTypeDesc.put(944, "Cyrillic (MOI8-R)");
				mapTypeDesc.put(945, "Cyrillic Text (DOS)");
				mapTypeDesc.put(946, "Cyrillic Text (ISO)");
				mapTypeDesc.put(947, "Cyrillic Text (KOI8-R)");
				mapTypeDesc.put(948, "Cyrillic Text (Mac)");
				mapTypeDesc.put(949, "Cyrillic Text (Win ANSI 1251)");
				mapTypeDesc.put(950, "US/Portuguese EBCDIC");
				mapTypeDesc.put(951, "Austrian/German EBCDIC");
				mapTypeDesc.put(952, "Danish/Norwegian EBCDIC");
				mapTypeDesc.put(953, "Finnish/Swedish EBCDIC");
				mapTypeDesc.put(954, "Italian EBCDIC");
				mapTypeDesc.put(955, "Spanish EBCDIC");
				mapTypeDesc.put(956, "UK English EBCDIC");
				mapTypeDesc.put(957, "French EBCDIC");
				mapTypeDesc.put(958, "Belgian/International EBCDIC");
				mapTypeDesc.put(959, "East Europe EBCDIC");
				mapTypeDesc.put(960, "Icelandic EBCDIC");
				mapTypeDesc.put(961, "Turkish EBCDIC");
				mapTypeDesc.put(962, "Greek Text (ISO)");
				mapTypeDesc.put(963, "Greek Text (Mac)");
				mapTypeDesc.put(964, "Greek Text (Win)");
				mapTypeDesc.put(965, "Hebrew Text (DOS)");
				mapTypeDesc.put(966, "Hebrew Text (VAX EO)");
				mapTypeDesc.put(967, "Hebrew Text (ISO)");
				mapTypeDesc.put(968, "Hebrew Text (7-bit)");
				mapTypeDesc.put(969, "Hebrew Text (IBM PC8)");
				mapTypeDesc.put(970, "Hebrew Text (Win)");
				mapTypeDesc.put(971, "Hex");
				mapTypeDesc.put(972, "Japanese Text (JIS)");
				mapTypeDesc.put(973, "Japanese Text (Mac)");
				mapTypeDesc.put(974, "Japanese Text (Win)");
				mapTypeDesc.put(975, "Japanese EUC");
				mapTypeDesc.put(976, "Japanese Shift JIS");
				mapTypeDesc.put(977, "Korean Hangeul");
				mapTypeDesc.put(978, "Korean Text (Win ANSI 1361)");
				mapTypeDesc.put(979, "Korean Text (Win ANSI 949)");
				mapTypeDesc.put(980, "Latin 2");
				mapTypeDesc.put(981, "Mac 7");
				mapTypeDesc.put(982, "Mac 8");
				mapTypeDesc.put(983, "Russian Text (DOS OEM 866)");
				mapTypeDesc.put(984, "Thai Text (Win ANSI 874)");
				mapTypeDesc.put(985, "Turkish Text (DOS OEM 857)");
				mapTypeDesc.put(986, "Turkish Text (ISO 8859-9)");
				mapTypeDesc.put(987, "Turkish Text (Mac)");
				mapTypeDesc.put(988, "Turkish Text (Win ANSI 1254)");
				mapTypeDesc.put(989, "UTF-8 encoded Text");
				mapTypeDesc.put(990, "UUE Encoded Text");
				mapTypeDesc.put(991, "UUE Encoded Continued Part");
				mapTypeDesc.put(992, "Vietnamese Text (Win ANSI 1258)");
				mapTypeDesc.put(993, "West Europe Text (ISO 8859-1)");
				mapTypeDesc.put(994, "West Europe Text (Mac)");
				mapTypeDesc.put(995, "West Europe Text (Win ANSI 1252)");
				mapTypeDesc.put(996, "XXE Encoded Text");
				mapTypeDesc.put(997, "XXE Encoded Continued Part");
				mapTypeDesc.put(998, "YEnc Encoded Text");
				mapTypeDesc.put(999, "YEnc Encoded Continued Part");
				mapTypeDesc.put(1000, "Unicode");
				mapTypeDesc.put(1001, "Unviewable");
				mapTypeDesc.put(1002, "IFF Text");
				mapTypeDesc.put(1003, "User Types");
				mapTypeDesc.put(1004, "MS Exchange Server");
				mapTypeDesc.put(1005, "Newly-decrypted Files");
				mapTypeDesc.put(1006, "Thumbcache DB Entries");
				mapTypeDesc.put(1007, "Index.dat Entries");
				mapTypeDesc.put(1008, "Empty Index.dat");
				mapTypeDesc.put(1009, "AOL ABY Files");
				mapTypeDesc.put(1010, "AOL TMB LST Files");
				mapTypeDesc.put(1011, "Thumbcache DB Files");
				mapTypeDesc.put(1012, "3GPP Files");
				mapTypeDesc.put(1013, "Excel 97 Stream");
				mapTypeDesc.put(1014, "OLE Files");
				mapTypeDesc.put(1015, "Other Encryption Files");
				mapTypeDesc.put(1016, "EFS Key Files");
				mapTypeDesc.put(1017, "Internet/Chat Files");
				mapTypeDesc.put(1018, "Internet Explorer Files");
				mapTypeDesc.put(1019, "Netscape Files");
				mapTypeDesc.put(1020, "OS/File System Files");
				mapTypeDesc.put(1021, "Embedded Graphics");
				mapTypeDesc.put(1022, "WordPerfect Envoy Files");
				mapTypeDesc.put(1023, "Word 97 Stream");
				mapTypeDesc.put(1024, "Excel 2007 Binary");
				mapTypeDesc.put(1025, "Remote Drive");
				mapTypeDesc.put(1026, "Webmail Files");
				mapTypeDesc.put(1027, "SearchML 3.2");
				mapTypeDesc.put(1028, "Microsoft DRM");
				mapTypeDesc.put(1029, "Microsoft DRM");
				mapTypeDesc.put(1030, "Microsoft Word DRM");
				mapTypeDesc.put(1031, "Micrsoft Word 2007/2010 DRM");
				mapTypeDesc.put(1032, "Oracle IRM");
				mapTypeDesc.put(1033, "Oracle IRM Document");
				mapTypeDesc.put(1034, "Microsoft Excel DRM");
				mapTypeDesc.put(1035, "Microsoft Excel 2007/2010 DRM");
				mapTypeDesc.put(1036, "Microsoft PowerPoint DRM");
				mapTypeDesc.put(1037, "Microsoft PowerPoint 2007/2010 DRM");
				mapTypeDesc.put(1038, "Autodesk DWF");
				mapTypeDesc.put(1039, "Corel Draw 12.0");
				mapTypeDesc.put(1040, "JPEG 2000");
				mapTypeDesc.put(1041, "OASIS OpenDocument 1.0");
				mapTypeDesc.put(1042, "Flexiondoc 5.2");
				mapTypeDesc.put(1043, "Windows Event Log");
				mapTypeDesc.put(1044, "PFX / PKCS12 File");
				mapTypeDesc.put(1045, "Mobile Phone Data");
				mapTypeDesc.put(1046, "Lotus Notes Database");
				mapTypeDesc.put(1047, "Lotus Notes Mailbox");
				mapTypeDesc.put(1048, "Steganography Applications");
				mapTypeDesc.put(1049, "Lotus Notes user key file");
				mapTypeDesc.put(1050, "Credant Encrypted");
				mapTypeDesc.put(1051, "Credant Keys");
				mapTypeDesc.put(1052, "Netscape Form History");
				mapTypeDesc.put(1053, "Netscape MSG");
				mapTypeDesc.put(1054, "Logical Images");
				mapTypeDesc.put(1055, "Physical Images");
				mapTypeDesc.put(1056, "AccessData AD1 Image");
				mapTypeDesc.put(1057, "Firefox Files");
				mapTypeDesc.put(1058, "SQLITE Database");
				mapTypeDesc.put(1059, "Firefox Cookies Index");
				mapTypeDesc.put(1060, "Not Verified");
				mapTypeDesc.put(1061, "Firefox Form History");
				mapTypeDesc.put(1062, "Firefox Places Database");
				mapTypeDesc.put(1063, "Windows Media Audio");
				mapTypeDesc.put(1064, "Windows Media Video");
				mapTypeDesc.put(1065, "Firefox downloads database");
				mapTypeDesc.put(1066, "Firefox search database");
				mapTypeDesc.put(1067, "Firefox Permissions Database");
				mapTypeDesc.put(1068, "MS Money 98 File");
				mapTypeDesc.put(1069, "MS Money 2000 File");
				mapTypeDesc.put(1070, "Access 2000 File");
				mapTypeDesc.put(1071, "Access 2000 System File");
				mapTypeDesc.put(1072, "Access 2007/2010 File");
				mapTypeDesc.put(1073, "Access 2 System File");
				mapTypeDesc.put(1074, "Access 7 System File");
				mapTypeDesc.put(1075, "Jet Database");
				mapTypeDesc.put(1076, "MS Jet Database");
				mapTypeDesc.put(1077, "MS Jet 2 Database");
				mapTypeDesc.put(1078, "MS Jet 3 Database");
				mapTypeDesc.put(1079, "MS Jet 4 Database");
				mapTypeDesc.put(1080, "MS Jet 5 Database");
				mapTypeDesc.put(1081, "Property list file");
				mapTypeDesc.put(1082, "Remote File System");
				mapTypeDesc.put(1083, "Phonebook");
				mapTypeDesc.put(1084, "Messages");
				mapTypeDesc.put(1085, "Call History");
				mapTypeDesc.put(1086, "Calendar");
				mapTypeDesc.put(1087, "PHP HTML");
				mapTypeDesc.put(1088, "MPEG 4.0 Video");
				mapTypeDesc.put(1089, "MPEG 7.0 Video");
				mapTypeDesc.put(1090, "Advanced Streaming Format");
				mapTypeDesc.put(1091, "Microsoft Digital Video Recording");
				mapTypeDesc.put(1092, "Real Media");
				mapTypeDesc.put(1093, "JSON file");
				mapTypeDesc.put(1094, "OCR Extractions");
				mapTypeDesc.put(1095, "Digital Camera Image");
				mapTypeDesc.put(1096, "NSF Misc Note");
				mapTypeDesc.put(1097, "NSF Stub Note");
				mapTypeDesc.put(1098, "Certificates");
				mapTypeDesc.put(1099, "DER Certificate");
				mapTypeDesc.put(1100, "Base64 Certificate");
				mapTypeDesc.put(1101, "Public Key");
				mapTypeDesc.put(1102, "Private Key");
				mapTypeDesc.put(1103, "PKCS7 Certificate");
				mapTypeDesc.put(1104, "PEM Certificate");
				mapTypeDesc.put(1105, "PKCS7 / SMIME Files");
				mapTypeDesc.put(1106, "PKCS7 Data");
				mapTypeDesc.put(1107, "PKCS7 Encrypted Data");
				mapTypeDesc.put(1108, "PKCS7 Digest");
				mapTypeDesc.put(1109, "PKCS7 Signature");
				mapTypeDesc.put(1110, "PKCS7 Signed Data");
				mapTypeDesc.put(1111, "Blackberry IPD");
				mapTypeDesc.put(1112, "Lotus Notes secret key file");
				mapTypeDesc.put(1113, "Apple iWork Document");
				mapTypeDesc.put(1114, "Apple iWork Presentation");
				mapTypeDesc.put(1115, "Apple iWork Spreadsheet");
				mapTypeDesc.put(1116, "PowerPoint 2010");
				mapTypeDesc.put(1117, "PowerPoint 2010 Template");
				mapTypeDesc.put(1118, "Encrypted PowerPoint 2010");
				mapTypeDesc.put(1119, "Microsoft Project 2007");
				mapTypeDesc.put(1120, "Microsoft Project 2010");
				mapTypeDesc.put(1121, "Microsoft Word 2010");
				mapTypeDesc.put(1122, "Word Template 2010");
				mapTypeDesc.put(1123, "Encrypted Word 2010");
				mapTypeDesc.put(1124, "Encrypted Excel 2007 Binary");
				mapTypeDesc.put(1125, "Excel 2010");
				mapTypeDesc.put(1126, "Excel 2010 Template");
				mapTypeDesc.put(1127, "Excel 2010 Binary");
				mapTypeDesc.put(1128, "Encrypted Excel 2010 Spreadsheets");
				mapTypeDesc.put(1129, "Encrypted Excel 2010 Binary");
				mapTypeDesc.put(1130, "OpenOffice Writer 3");
				mapTypeDesc.put(1131, "StarOffice Writer 9");
				mapTypeDesc.put(1132, "Oracle OpenOffice Writer 3");
				mapTypeDesc.put(1133, "JungUm Document");
				mapTypeDesc.put(1134, "Kingsoft Writer");
				mapTypeDesc.put(1135, "Word 2010 Macro-Enabled Document");
				mapTypeDesc.put(1136, "Word 2010 Macro-Enabled Temlate Document");
				mapTypeDesc.put(1137, "Excel 2003 XML");
				mapTypeDesc.put(1138, "OpenOffice Calc 3");
				mapTypeDesc.put(1139, "Quattro Pro X4 NB");
				mapTypeDesc.put(1140, "Excel 2007 Add-in Macro");
				mapTypeDesc.put(1141, "DIF Spreadsheet");
				mapTypeDesc.put(1142, "StarOffice Calc 9");
				mapTypeDesc.put(1143, "Oracle OpenOffice Calc 3");
				mapTypeDesc.put(1144, "Kingsoft Spreadsheet");
				mapTypeDesc.put(1145, "Excel 2010 Macro");
				mapTypeDesc.put(1146, "Excel 2010 Macro Template");
				mapTypeDesc.put(1147, "Excel 2010 Add-In Macro");
				mapTypeDesc.put(1148, "RIFF File");
				mapTypeDesc.put(1149, "OneNote 2007 Package");
				mapTypeDesc.put(1150, "WMP Playlist");
				mapTypeDesc.put(1151, "Flexiondoc 5.4 schema");
				mapTypeDesc.put(1152, "Flexiondoc");
				mapTypeDesc.put(1153, "OpenOffice Impress 3");
				mapTypeDesc.put(1154, "OpenOffice Draw 3");
				mapTypeDesc.put(1155, "Presentations X4");
				mapTypeDesc.put(1156, "Access Report Snapshot");
				mapTypeDesc.put(1157, "StarOffice Impress 9");
				mapTypeDesc.put(1158, "StarOffice Draw 9");
				mapTypeDesc.put(1159, "Oracle OpenOffice Impress 3");
				mapTypeDesc.put(1160, "Oracle OpenOffice Draw 3");
				mapTypeDesc.put(1161, "Powerpoint 2010 Macro Template");
				mapTypeDesc.put(1162, "PowerPoint 2010 Slide Show");
				mapTypeDesc.put(1163, "PowerPoint 2010 Macro");
				mapTypeDesc.put(1164, "PowerPoint 2010 Macro Slide Show");
				mapTypeDesc.put(1165, "OneNote 2007 Document");
				mapTypeDesc.put(1166, "OneNote 2007 ONETOC2 Document");
				mapTypeDesc.put(1167, "7-Zip");
				mapTypeDesc.put(1168, "MTS Video");
				mapTypeDesc.put(1169, "M2TS Video");
				mapTypeDesc.put(1170, "Facebook");
				mapTypeDesc.put(1171, "Facebook Chat History");
				mapTypeDesc.put(1172, "Windows Vista/7 Event Log");
				mapTypeDesc.put(1173, "Windows Vista/7 Event");
				mapTypeDesc.put(1174, "BestCrypt Archive");
				mapTypeDesc.put(1175, "BestCrypt TextEncoder");
				mapTypeDesc.put(1176, "Generic Open Document Format");
				mapTypeDesc.put(1177, "AdvancedFileLock Encryption");
				mapTypeDesc.put(1178, "ABI-CODER Encryption");
				mapTypeDesc.put(1179, "AIM (AOL Instant Messenger) Triton");
				mapTypeDesc.put(1180, "AIM (AOL Instant Messenger) For Windows");
				mapTypeDesc.put(1181, "AOL Desktop Database");
				mapTypeDesc.put(1182, "AIM (AOL Instant Messenger) PostgreSQL Password Database");
				mapTypeDesc.put(1183, "BestCrypt Header");
				mapTypeDesc.put(1184, "BestCrypt Backup");
				mapTypeDesc.put(1185, "BestCrypt Volume");
				mapTypeDesc.put(1186, "Bestcrypt Volume Rescue");
				mapTypeDesc.put(1187, "TrueCrypt Boot Volume");
				mapTypeDesc.put(1188, "TrueCrypt Boot Volume Rescue Disk");
				mapTypeDesc.put(1189, "DiskCryptor Boot Volume");
				mapTypeDesc.put(1190, "DiskCryptor Boot Volume (Old Format)");
				mapTypeDesc.put(1191, "TrueCrypt Volume");
				mapTypeDesc.put(1192, "IIS Logs");
				mapTypeDesc.put(1193, "IIS Log Entries");
				mapTypeDesc.put(1194, "");
				mapTypeDesc.put(1195, "Registry Values");
				mapTypeDesc.put(1196, "Access 2000/2002/2003");
				mapTypeDesc.put(1197, "Access 2007/2010");
				mapTypeDesc.put(1198, "Access Web Database");
				mapTypeDesc.put(1199, "Access 2007/2010 Template File");
				mapTypeDesc.put(1200, "Trillian Text Log File");
				mapTypeDesc.put(1201, "Trillian XML Log File");
				mapTypeDesc.put(1202, "Microsoft Live Messenger Log File");
				mapTypeDesc.put(1203, "AOL Messenger Log File");
				mapTypeDesc.put(1204, "Apple iWork Pages Preview");
				mapTypeDesc.put(1205, "SearchML 3.5");
				mapTypeDesc.put(1206, "S/MIME (Secure MIME)");
				mapTypeDesc.put(1207, "Clear Signed S/MIME");
				mapTypeDesc.put(1208, "Microsoft Word 2013");
				mapTypeDesc.put(1209, "Word Template 2013");
				mapTypeDesc.put(1210, "Word 2013 Macro-Enabled Document");
				mapTypeDesc.put(1211, "Word 2013 Macro-Enabled Template");
				mapTypeDesc.put(1212, "Quattro Pro X5 NB");
				mapTypeDesc.put(1213, "Apple iWork Numbers File Preview");
				mapTypeDesc.put(1214, "Excel 2007 XML");
				mapTypeDesc.put(1215, "Excel 2013");
				mapTypeDesc.put(1216, "Excel 2013 Macro");
				mapTypeDesc.put(1217, "Excel 2013 Template");
				mapTypeDesc.put(1218, "Excel 2013 Macro Template");
				mapTypeDesc.put(1219, "Excel 2013 Add-in Macro");
				mapTypeDesc.put(1220, "Excel 2013 Binary");
				mapTypeDesc.put(1221, "Flash 9");
				mapTypeDesc.put(1222, "Flash 10");
				mapTypeDesc.put(1223, "7-Zip Self Extracting Archive");
				mapTypeDesc.put(1224, "Flexiondoc 5.5 schema");
				mapTypeDesc.put(1225, "AutoCAD 2010");
				mapTypeDesc.put(1226, "Presentations X5");
				mapTypeDesc.put(1227, "Apple iWork Keynote File Preview");
				mapTypeDesc.put(1228, "Scalable Vector Graphics");
				mapTypeDesc.put(1229, "Autodesk DWF Archive");
				mapTypeDesc.put(1230, "PowerPoint 2013");
				mapTypeDesc.put(1231, "PowerPoint 2013 Template");
				mapTypeDesc.put(1232, "PowerPoint 2013 Macro Template");
				mapTypeDesc.put(1233, "PowerPoint 2013 Slide Show");
				mapTypeDesc.put(1234, "PowerPoint 2013 Macro");
				mapTypeDesc.put(1235, "PowerPoint 2013 Macro Slide Show");
				mapTypeDesc.put(1236, "Windows Explorer Command File");
				mapTypeDesc.put(1237, "Windows Compiled Help File");
				mapTypeDesc.put(1238, "TrueType Font");
				mapTypeDesc.put(1239, "TrueType Font Collection");
				mapTypeDesc.put(1240, "TrueType MAC Font");
			}
		}

		String desc = mapTypeDesc.get(type);
		if (desc == null)
			desc = "Outros";
		return desc;
	}

}
