package iped.parsers.eventtranscript;

public final class DBQueries {

    public static final String HISTORY_QUERY = "SELECT"
        + " UserSID,"
        + " json_extract(JSONPayload,'$.data.CorrelationGuid') AS CorrelationGuid,"
        + " Timestamp,"
        + " replace(group_concat(DISTINCT TagName), ',', ';') AS TagNames,"
        + " replace(group_concat(DISTINCT EventName), ',', ';') AS EventNames,"
        + " URL,"
        + " App,"
        + " replace(group_concat(DISTINCT nullif(PageTitle, '')), ',', ';') AS PageTitles,"
        + " JSONPayload"
        + " FROM ("
        + " SELECT events_persisted.sid AS UserSID,"
        + "     datetime((events_persisted.timestamp/10000000) - 11644473600, 'unixepoch', 'UTC') AS Timestamp,"
        + "     tag_descriptions.tag_name AS TagName,"
        + "     events_persisted.full_event_name AS FullEventName,"
        + "     replace(replace(substr(distinct events_persisted.full_event_name,39),'Microsoft.',''),'WebBrowser.HistoryJournal.HJ_','') AS 'EventName',"
        + "     json_extract(events_persisted.payload,'$.ext.app.name') AS App,"
        + "     events_persisted.compressed_payload_size AS CompressedPayloadSize,"
        + "     json_extract(events_persisted.payload,'$.data.navigationUrl') AS URL,"
        + "     json_extract(events_persisted.payload,'$.data.PageTitle') AS PageTitle,"
        + "     events_persisted.payload AS JSONPayload"
        + " FROM"
        + "     events_persisted"
        + "     LEFT JOIN event_tags ON events_persisted.full_event_name_hash = event_tags.full_event_name_hash"
        + "     LEFT JOIN tag_descriptions ON event_tags.tag_id = tag_descriptions.tag_id"
        + "     INNER JOIN provider_groups ON events_persisted.provider_group_id = provider_groups.group_id"
        + " WHERE"
        + "     (tag_descriptions.tag_name='Browsing History' AND events_persisted.full_event_name LIKE '%HistoryAddUrl') OR"
        + "     (tag_descriptions.tag_name='Product and Service Usage' AND events_persisted.full_event_name LIKE '%HistoryAddUrlEx')"
        + " )"
        + " GROUP BY CorrelationGuid"
        + " ORDER BY Timestamp DESC";


        public static final String INVENTORY_APPS_QUERY = "SELECT"
        + " datetime( ( events_persisted.timestamp / 10000000 ) - 11644473600, 'unixepoch' ) AS 'Timestamp',"
        + " json_extract(events_persisted.payload,'$.ext.utc.seq') as 'seq', "
        + " tag_descriptions.tag_name AS TagName,"
        + " replace(events_persisted.full_event_name,'Microsoft.Windows.Inventory.Core.Inventory','') as 'EventName',"
        + " events_persisted.full_event_name as 'FullEventName',"
        + " json_extract(events_persisted.payload,'$.data.Type') as 'Type',"
        + " json_extract(events_persisted.payload,'$.data.Name') as 'Name',"
        + " json_extract(events_persisted.payload,'$.data.PackageFullName') as 'PackageFullName',"
        + " json_extract(events_persisted.payload,'$.data.Version') as 'Version',"
        + " json_extract(events_persisted.payload,'$.data.Publisher') as 'Publisher',"
        + " json_extract(events_persisted.payload,'$.data.RootDirPath') as 'RootDirPath',"
        + " json_extract(events_persisted.payload,'$.data.HiddenArp') as 'HiddenArp',"
        + " json_extract(events_persisted.payload,'$.data.InstallDate') as 'InstallDate',"
        + " json_extract(events_persisted.payload,'$.data.Source') as 'Source',"
        + " json_extract(events_persisted.payload,'$.data.OSVersionAtInstallTime') as 'OSVersionAtInstallTime',"
        + " json_extract(events_persisted.payload,'$.data.InstallDateMsi') as 'MsiInstallDate',"
        + " json_extract(events_persisted.payload,'$.data.MsiPackageCode') as 'MsiPackageCode',"
        + " json_extract(events_persisted.payload,'$.data.MsiProductCode') as 'MsiProductCode',"
        + " case json_extract(events_persisted.payload,'$.data.baseData.action') "
        + "     when 1 then 'Add'"
        + "     when 2 then 'Remove'"
        + "     else json_extract(events_persisted.payload,'$.data.baseData.action') "
        + " end as 'action',"
        + " json_extract(events_persisted.payload,'$.data.baseData.objectInstanceId') as 'InstanceId',"
        + " trim(json_extract(events_persisted.payload,'$.ext.user.localId'),'m:') as 'UserId',"
        + " sid as 'UserSID',"
        + " events_persisted.payload AS JSONPayload"
        + " FROM"
        + "     events_persisted"
        + "     LEFT JOIN event_tags ON events_persisted.full_event_name_hash = event_tags.full_event_name_hash"
        + "     LEFT JOIN tag_descriptions ON event_tags.tag_id = tag_descriptions.tag_id"
        + " WHERE"
        + " events_persisted.full_event_name like 'Microsoft.Windows.Inventory.Core.Inventory%' and"
        + " TagName = 'Software Setup and Inventory'"
        + " order by cast(events_persisted.timestamp as integer) desc";
}
